/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class au_com_pharos_gdbm_GdbmFile */

#ifndef _Included_au_com_pharos_gdbm_GdbmFile
#define _Included_au_com_pharos_gdbm_GdbmFile
#ifdef __cplusplus
extern "C" {
#endif
#undef au_com_pharos_gdbm_GdbmFile_READER
#define au_com_pharos_gdbm_GdbmFile_READER 0L
#undef au_com_pharos_gdbm_GdbmFile_WRITER
#define au_com_pharos_gdbm_GdbmFile_WRITER 1L
#undef au_com_pharos_gdbm_GdbmFile_WRCREAT
#define au_com_pharos_gdbm_GdbmFile_WRCREAT 2L
#undef au_com_pharos_gdbm_GdbmFile_NEWDB
#define au_com_pharos_gdbm_GdbmFile_NEWDB 3L
#undef au_com_pharos_gdbm_GdbmFile_FAST
#define au_com_pharos_gdbm_GdbmFile_FAST 16L
/*
 * Class:     au_com_pharos_gdbm_GdbmFile
 * Method:    gdbm_open
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_au_com_pharos_gdbm_GdbmFile_gdbm_1open
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     au_com_pharos_gdbm_GdbmFile
 * Method:    gdbm_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_au_com_pharos_gdbm_GdbmFile_gdbm_1close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     au_com_pharos_gdbm_GdbmFile
 * Method:    gdbm_store
 * Signature: (J[B[BZ)V
 */
JNIEXPORT void JNICALL Java_au_com_pharos_gdbm_GdbmFile_gdbm_1store
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jboolean);

/*
 * Class:     au_com_pharos_gdbm_GdbmFile
 * Method:    gdbm_fetch
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_au_com_pharos_gdbm_GdbmFile_gdbm_1fetch
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     au_com_pharos_gdbm_GdbmFile
 * Method:    gdbm_exists
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_au_com_pharos_gdbm_GdbmFile_gdbm_1exists
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     au_com_pharos_gdbm_GdbmFile
 * Method:    gdbm_delete
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_au_com_pharos_gdbm_GdbmFile_gdbm_1delete
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     au_com_pharos_gdbm_GdbmFile
 * Method:    gdbm_firstkey
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_au_com_pharos_gdbm_GdbmFile_gdbm_1firstkey
  (JNIEnv *, jobject, jlong);

/*
 * Class:     au_com_pharos_gdbm_GdbmFile
 * Method:    gdbm_nextkey
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_au_com_pharos_gdbm_GdbmFile_gdbm_1nextkey
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     au_com_pharos_gdbm_GdbmFile
 * Method:    gdbm_getversion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_au_com_pharos_gdbm_GdbmFile_gdbm_1getversion
  (JNIEnv *, jclass);

/*
 * Class:     au_com_pharos_gdbm_GdbmFile
 * Method:    gdbm_wrapperVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_au_com_pharos_gdbm_GdbmFile_gdbm_1wrapperVersion
  (JNIEnv *, jclass);

/*
 * Class:     au_com_pharos_gdbm_GdbmFile
 * Method:    gdbm_reorganize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_au_com_pharos_gdbm_GdbmFile_gdbm_1reorganize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     au_com_pharos_gdbm_GdbmFile
 * Method:    gdbm_sync
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_au_com_pharos_gdbm_GdbmFile_gdbm_1sync
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class au_com_pharos_gdbm_GdbmFile_KeyEnumeration */

#ifndef _Included_au_com_pharos_gdbm_GdbmFile_KeyEnumeration
#define _Included_au_com_pharos_gdbm_GdbmFile_KeyEnumeration
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
